### ISSUE TITLE
Scrollbar keep on bottom

### ISSUE THREAD

**Issue by wesleywong** [rochal/jQuery-slimScroll#51]
I used it for the chat function which is dynamic content and i need to keep the scrollbar always on the bottom of content (latest content always from the bottom). How should i do this from this plugin?

**Comment by joncombe** [comment]
Two years too late for the original question but I found the solution to this problem.

I was having exactly the same issue as ddctd143 describes. Turns out, the element must be referenced by it's ID for this to work.
Bad: `$('#myelem > div').slimScroll({ scrollTo: '140px' })`
Good: `$('#myinnerelem').slimScroll({ scrollTo: '140px' })`

**Comment by DeepzSandra** [comment]
hi joncombe,
  i use the same solution but not working

**Comment by mrsoftware** [comment]
@rochal thanks but . 
`  $('#testDiv').slimScroll({ scrollBy: height * 2  });`
is better.
